# Generated by Django 4.2.20 on 2025-03-08 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('niveau', models.CharField(max_length=10)),
                ('filiere', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'etudiant',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('coefficient', models.IntegerField()),
                ('etudiant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_etudiant', to='GestionEtudiantApp.etudiant')),
            ],
            options={
                'db_table': 'matiere',
            },
        ),
    ]
