# Generated by Django 4.2.20 on 2025-03-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEtudiantApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matiere',
            old_name='etudiant_id',
            new_name='etudiant',
        ),
    ]
