# Generated by Django 4.2.20 on 2025-03-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEtudiantApp', '0003_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
