# Generated by Django 4.2.20 on 2025-03-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEtudiantApp', '0004_alter_etudiant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='niveau',
            field=models.CharField(max_length=25),
        ),
    ]
